name: Tic Tac Toe Tester

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml  # If you need XML reports for further integrations

    - name: Upload coverage to a coverage reporting service
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml  # or htmlcov/ if uploading HTML reports
